<%@ Page Title="" Language="C#" MasterPageFile="~/OLEMS.Master" AutoEventWireup="true" CodeBehind="ExamManagement.aspx.cs" Inherits="OLEMS.ExamManagement.ExamManagement1" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:DetailsView ID="ExamDetailsView" runat="server" AutoGenerateRows="False" CellPadding="4" 
        DataKeyNames="id" DataSourceID="Exam_SqlDataSource" DefaultMode="Insert" 
        ForeColor="#333333" GridLines="None" Height="50px" Width="473px" 
        oniteminserted="ExamDetailsView_ItemInserted" 
        oniteminserting="ExamDetailsView_ItemInserting">
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <Fields>
            <asp:TemplateField HeaderText="Exam Type" SortExpression="examTypeId">
                <InsertItemTemplate>
                    <asp:DropDownList ID="examTypeDropDownList" runat="server" DataSourceID="ExamType_SqlDataSource"
                        AppendDataBoundItems="true" SelectedValue='<%#Bind("examTypeId")%>'
                        DataMember="DefaultView" DataTextField="name" DataValueField="id">
                    </asp:DropDownList>
                </InsertItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Name" SortExpression="Name">
                <InsertItemTemplate>
                    <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("Name") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVName" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter name" ControlToValidate="txtName"
                        Font-Names="Arial" Font-Size="Small" SetFocusOnError="true">
                    </asp:RequiredFieldValidator>
                </InsertItemTemplate>
            </asp:TemplateField>                
            <asp:TemplateField HeaderText="Duration" SortExpression="Duration">
                <InsertItemTemplate>
                    <asp:TextBox ID="txtDuration" runat="server" Text='<%# Bind("Duration") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVDuration" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter duration" ControlToValidate="txtDuration"
                        Font-Names="Arial" Font-Size="Small">
                    </asp:RequiredFieldValidator>
                    <asp:RangeValidator Display="Dynamic" ID="valGVDuration" runat="server" ValidationGroup="GV"
                        ControlToValidate="txtDuration" MaximumValue="250" MinimumValue="1" Type="Integer"
                        Font-Names="Arial" Font-Size="Small"> Duration should be between 1-250
                    </asp:RangeValidator>
                </InsertItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tolerance" SortExpression="Tolerance">
                <InsertItemTemplate>
                    <asp:TextBox ID="txtTolerance" runat="server" Text='<%# Bind("Tolerance") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVTolerance" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter tolerance" ControlToValidate="txtTolerance"
                        Font-Names="Arial" Font-Size="Small">
                    </asp:RequiredFieldValidator>                 
                </InsertItemTemplate>
            </asp:TemplateField>
            <asp:CheckBoxField DataField="isActive" HeaderText="Active" 
                SortExpression="isActive" />
            <asp:CommandField ShowInsertButton="True" ValidationGroup="GV" />
        </Fields>
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" />
    </asp:DetailsView>
    <asp:GridView ID="ExamGridView" runat="server" AllowPaging="True" 
        AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="id" 
        DataSourceID="Exam_SqlDataSource" ForeColor="#333333" GridLines="None" 
        OnSelectedIndexChanging="ExamGridView_SelectedIndexChanging" Width="474px" 
        onrowdeleted="ExamGridView_RowDeleted" onrowdeleting="ExamGridView_RowDeleting" 
        onrowediting="ExamGridView_RowEditing" onrowupdated="ExamGridView_RowUpdated">
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <Columns>
            <asp:CommandField SelectText="Questions" ShowSelectButton="True" />
            <asp:TemplateField HeaderText="Exam Type" SortExpression="examTypeId">
                <ItemTemplate>
                    <asp:DropDownList ID="examTypeDropDownList" runat="server" DataSourceID="ExamType_SqlDataSource"
                        AppendDataBoundItems="true" SelectedValue='<%#Bind("examTypeId")%>'
                        DataMember="DefaultView" Enabled="false" DataTextField="name" DataValueField="id">
                    </asp:DropDownList>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:DropDownList ID="examTypeDropDownList2" runat="server" DataSourceID="ExamType_SqlDataSource"
                        AppendDataBoundItems="true" SelectedValue='<%#Bind("examTypeId")%>'
                        DataMember="DefaultView" Enabled="true" DataTextField="name" DataValueField="id">
                    </asp:DropDownList>
                </EditItemTemplate>                            
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Name" SortExpression="name">
                <EditItemTemplate>
                    <asp:TextBox ID="txtName2" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVName" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter name" ControlToValidate="txtName2"
                        Font-Names="Arial" Font-Size="Small" SetFocusOnError="true">
                    </asp:RequiredFieldValidator>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblName2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Duration" SortExpression="duration">
                <EditItemTemplate>
                    <asp:TextBox ID="txtDuration2" runat="server" Text='<%# Bind("duration") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVDuration" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter duration" ControlToValidate="txtDuration2"
                        Font-Names="Arial" Font-Size="Small">
                    </asp:RequiredFieldValidator>
                    <asp:RangeValidator Display="Dynamic" ID="valGVDuration" runat="server" ValidationGroup="GV"
                        ControlToValidate="txtDuration2" MaximumValue="250" MinimumValue="1" Type="Integer"
                        Font-Names="Arial" Font-Size="Small"> Duration should be between 1-250
                    </asp:RangeValidator>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblDuration2" runat="server" Text='<%# Bind("duration") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tolerance" SortExpression="tolerance">
                <EditItemTemplate>
                    <asp:TextBox ID="txtTolerance2" runat="server" Text='<%# Bind("tolerance") %>'></asp:TextBox>
                    <asp:RequiredFieldValidator Display="Dynamic" ID="reqValidatorGVTolerance" ValidationGroup="GV"
                        runat="server" ErrorMessage="Please enter tolerance" ControlToValidate="txtTolerance2"
                        Font-Names="Arial" Font-Size="Small">
                    </asp:RequiredFieldValidator> 
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblTolerance2" runat="server" Text='<%# Bind("tolerance") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:CheckBoxField DataField="isActive" HeaderText="Active" 
                SortExpression="isActive" />
            <asp:TemplateField HeaderText="id" SortExpression="id" Visible="False">
                <ItemTemplate>
                    <asp:Label ID="lblExamID" runat="server" Visible="false" Text='<%# Bind("id") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <AlternatingRowStyle BackColor="White" />
    </asp:GridView>
    <asp:SqlDataSource ID="Exam_SqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:IS50220082G4_ConnectionString %>" 
        SelectCommand="SELECT * FROM [Exam]" 
        UpdateCommand="UPDATE Exam SET examTypeId = @examTypeId, name = @name, duration = @duration, tolerance = @tolerance, isActive = @isActive WHERE (id = @id)"
        InsertCommand="INSERT INTO [Exam] (examTypeId, name, duration, tolerance, isActive) VALUES (@examTypeId, @name, @duration, @tolerance, @isActive)" 
        DeleteCommand="DELETE FROM [Exam]  WHERE id=@id">
        <DeleteParameters>
            <asp:Parameter Name="id" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="examTypeId" />
            <asp:Parameter Name="name" />
            <asp:Parameter Name="duration" />
            <asp:Parameter Name="tolerance" />
            <asp:Parameter Name="isActive" />
            <asp:Parameter Name="id" />
        </UpdateParameters>
        <InsertParameters>
            <asp:Parameter Name="examTypeId" />
            <asp:Parameter Name="name" />
            <asp:Parameter Name="duration" />
            <asp:Parameter Name="tolerance" />
            <asp:Parameter Name="isActive" />
        </InsertParameters>
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="ExamType_SqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:IS50220082G4_ConnectionString %>" 
        SelectCommand="SELECT [id], [name] FROM [ExamType]"></asp:SqlDataSource>
</asp:Content>
