//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Errors", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-mail Address!.
        /// </summary>
        internal static string invalidEmailAddress {
            get {
                return ResourceManager.GetString("invalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail addresses must be in the format of name@domain.xyz..
        /// </summary>
        internal static string invalidEmailFormat {
            get {
                return ResourceManager.GetString("invalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format!.
        /// </summary>
        internal static string invalidEmailFormatText {
            get {
                return ResourceManager.GetString("invalidEmailFormatText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be at least 4 and at most 8 characters long, and consist of alphanumeric characters..
        /// </summary>
        internal static string newPasswordRegularExpressionErrorMessage {
            get {
                return ResourceManager.GetString("newPasswordRegularExpressionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a different password..
        /// </summary>
        internal static string newPasswordRegularExpressionErrorMessage_original {
            get {
                return ResourceManager.GetString("newPasswordRegularExpressionErrorMessage_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new password of at least 4 and at most 8 alphanumeric characters..
        /// </summary>
        internal static string passwordHintText {
            get {
                return ResourceManager.GetString("passwordHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail address is required..
        /// </summary>
        internal static string requiredEmailAddress {
            get {
                return ResourceManager.GetString("requiredEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string requiredEmailAddressText {
            get {
                return ResourceManager.GetString("requiredEmailAddressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User e-mail updated..
        /// </summary>
        internal static string successfulEmailUpdate {
            get {
                return ResourceManager.GetString("successfulEmailUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username and/or password.
        /// </summary>
        internal static string unsuccessfulLoginAttempt {
            get {
                return ResourceManager.GetString("unsuccessfulLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please try again..
        /// </summary>
        internal static string unsuccessfulLoginAttempt_original {
            get {
                return ResourceManager.GetString("unsuccessfulLoginAttempt_original", resourceCulture);
            }
        }
    }
}
