<%@ Page Title="" Language="C#" MasterPageFile="~/OLEMS.Master" CodeBehind="SectionManagement.aspx.cs"
    Inherits="OLEMS.SectionManagement.CreateSection" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">    
    <%-- baslik-----------------------------------------------------------------------------------------------------%>   
     <body>
        <table width="100%">
            <tr>
                <td align="center" style="height: 21px">
                    <asp:Label ID="baslik" runat="server" Font-Bold="True" Font-Names="Arial" 
                     Font-Size ="Medium" ForeColor="#CC0000">SECTION MANAGEMENT
                    </asp:Label>
                </td>
            </tr>
            <tr>
                <td>
                <asp:SqlDataSource ID="Section_SqlDataSource" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:IS50220082G4_ConnectionString %>" 
                    SelectCommand="SELECT [name], [capacity], [id] FROM [Section]"
                    InsertCommand="INSERT INTO [Section] ([name],[capacity]) VALUES (@name,@capacity)"
                    UpdateCommand="UPDATE [Section] SET [name] = @name, [capacity] = @capacity WHERE [id] = @id"
                    DeleteCommand="DELETE FROM [Section] WHERE [id] = @id">
                    <InsertParameters>
                        <asp:Parameter Name="name" Type="Int16" />
                        <asp:Parameter Name="capacity" Type="Int16" />
                    </InsertParameters>  
                    <UpdateParameters>
                        <asp:Parameter Name="name" Type="Int16" />
                        <asp:Parameter Name="capacity" Type="Int16" />
                        <asp:Parameter Name="id" Type="Object" />
                    </UpdateParameters>
                    <DeleteParameters>
                        <asp:Parameter Name="id" Type="Object" />
                    </DeleteParameters>
                </asp:SqlDataSource>
                <asp:DetailsView ID="SectionDetailsView" runat="server" AllowPaging="True" 
                    AutoGenerateDeleteButton="True" AutoGenerateInsertButton="True" 
                    AutoGenerateRows="False" CellPadding="4" DataSourceID="Section_SqlDataSource" 
                    DefaultMode="Insert" ForeColor="#333333" Height="16px" Width="128px" 
                        Font-Names="Arial" Font-Size="Small" GridLines="None" 
                        HeaderText="Create Section" 
                        oniteminserted="SectionDetailsView_ItemInserted">
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <CommandRowStyle BackColor="#FFFFC0" Font-Bold="True" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <FieldHeaderStyle BackColor="#FFFF99" Font-Bold="True" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <Fields>
                        <asp:TemplateField HeaderText="Name" SortExpression="name">
                            <InsertItemTemplate>
                                <asp:TextBox ID="txtName" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                                    ErrorMessage="Section Name is required!" ControlToValidate="txtName" 
                                    Display="Dynamic"></asp:RequiredFieldValidator>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Capacity" SortExpression="capacity">
                            <InsertItemTemplate>
                                <asp:TextBox ID="txtCapacity" runat="server" Text='<%# Bind("capacity") %>'></asp:TextBox>
                            </InsertItemTemplate>
                        </asp:TemplateField>
                        <asp:CommandField ShowEditButton="True" />
                    </Fields>
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:DetailsView>
                
                </td>
        </tr>
        <tr>
            <td>
                <asp:LinkButton ID="lnkSearch" runat="server" Font-Bold="True" 
                Font-Names="Arial" Font-Size="Small" ForeColor="Black"  OnClick="lnkSearch_Click"
                ToolTip="Type section name and press button to search">Search Section(s)</asp:LinkButton>
        <asp:GridView ID="SectionGridView" runat="server" AllowPaging="True" AllowSorting="True"
                    AutoGenerateColumns="False" CellPadding="4" DataKeyNames="id" EmptyDataText="<B>No records found!</B>"
                    DataSourceID="Section_SqlDataSource" ForeColor="#333333" GridLines="None" Font-Names="Arial"
                    Font-Size="Small" OnRowEditing="SectionGridView_RowEditing" OnRowUpdated="SectionGridView_RowUpdated"
                    OnRowDeleted="SectionGridView_RowDeleted" Width="100%">
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <Columns>
                        <asp:CommandField ValidationGroup="GV" ShowEditButton="True">
                            <ControlStyle Font-Bold="True" />
                        </asp:CommandField>
                        <asp:CommandField ShowDeleteButton="True">
                            <ControlStyle Font-Bold="True" />
                        </asp:CommandField>
                        <asp:BoundField DataField="id" HeaderText="id" ReadOnly="True" SortExpression="id"
                            Visible="False" />
                        <asp:TemplateField HeaderText="Name" SortExpression="name">
                            <EditItemTemplate>
                                <asp:TextBox ID="txtSectionName" runat="server" Text='<%# Bind("name") %>'></asp:TextBox>
                                <asp:RangeValidator Display="Dynamic" ValidationGroup="GV" ID="reqValidator1"
                                   runat="server" ControlToValidate="txtSectionName" MaximumValue="255" MinimumValue="1" Type="Integer"
                                    ErrorMessage="Please enter Section name"
                                    Font-Names="Arial" Font-Size="Small"> Section name should be between 1-255
                                </asp:RangeValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("name") %>'></asp:Label>
                            </ItemTemplate>
                            <HeaderStyle Font-Italic="False" Wrap="False" />
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Capacity" SortExpression="capacity">
                            <EditItemTemplate>
                                <asp:TextBox ID="tCapacity" runat="server" Text='<%# Bind("capacity") %>'></asp:TextBox>
                                <asp:RangeValidator Display="Dynamic" ID="valCapacity" ValidationGroup="GV" runat="server"
                                    ControlToValidate="tCapacity" MaximumValue="255" MinimumValue="1" Type="Integer"
                                    Font-Names="Arial" Font-Size="Small"> Capacity should be between 1-255
                                </asp:RangeValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("capacity") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="createdBy" HeaderText="createdBy" SortExpression="createdBy"
                            Visible="False" />
                        <asp:BoundField DataField="createdAt" HeaderText="createdAt" SortExpression="createdAt"
                            Visible="False" />
                    </Columns>
                    <EmptyDataRowStyle ForeColor="Red" />
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" HorizontalAlign="Left"
                        Width="100px" Wrap="True" />
                    <AlternatingRowStyle BackColor="White" />
        </asp:GridView>
            </td>
        </tr>
        <tr>
            <td>
                </td>
        </tr>
        </table>
    </body>    
</asp:Content>
